name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

  workflow_dispatch:
  
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode version
        run: xcodebuild -version

      - name: Build
        run: xcodebuild build
            -scheme iOSTraining 
            -sdk iphonesimulator 
            -configuration Debug 
            -clonedSourcePackagesDirPath SourcePackages
