name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode version
        run: echo Hello, world!

      - name: Xcode Build
        run: xcodebuild -sdk iphonesimulator -configuration Debug build
